language: go

go:
  - "1.11"
  - "1.12"
  - master

install: true

before_script:
  - go get golang.org/x/lint/golint

script:
  - env GO111MODULE=on go test -v -cover ./...
  - env GO111MODULE=on go vet ./...
  - env GO111MODULE=on golint -set_exit_status $(go list ./... | grep -v /vendor/)
